[project]
name = "serialize-price"
authors = ["Web3 Oracle Team"]
description = "Decentralized Price Oracle for Secure Price Serialization"
telemetry = false
requirements = []

[contracts.price-oracle]
path = "contracts/price-oracle.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
